name: Generate Readme Stats 

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats (Dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=rajnishanand&show_icons=true&theme=github_dark&bg_color=ffffff00&text_color=a4bbd0&border_radius=0&hide_border=true&include_all_commits=true&rank_icon=percentile&card_width=400
          path: assets/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Stats (Light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=rajnishanand&show_icons=true&theme=github_dark&bg_color=ffffff00&text_color=535353&border_radius=0&hide_border=true&include_all_commits=true&rank_icon=percentile&card_width=400
          path: assets/stats-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate Top Langs (Dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=RajnishAnand&theme=github_dark&bg_color=ffffff00&text_color=a4bbd0&border_radius=0&hide_border=true&layout=compact&card_width=350
          path: assets/langs-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Langs (Light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=RajnishAnand&theme=github_dark&bg_color=ffffff00&text_color=535353&border_radius=0&hide_border=true&layout=compact&card_width=350
          path: assets/langs-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add assets/*.svg
          git commit -m "Update stats" || exit 0
          git push
